### ISSUE TITLE
Hover doesnot work properly when -transform-rotate is done

### ISSUE THREAD

**Issue by omkark** [CSS-Tricks/AnythingZoomer#28]
When image is loaded for the first time, hover window propersly shows the zoomed part wherever we hover.

But when i dynamically rotate image using -transform-rotate and then hover over any section, it is showing zoom window at other direction

Please help me

**Comment by Mottie** [comment]
Hi @omkark!

Whatever rotation that is applied to the small image should also be applied to the large image ([demo](http://jsfiddle.net/Mottie/f6d49/57/)).

```css
.large img {
    width: 500px;
    height: 333px;
    transform: rotate(10deg);
}
.small img {
    width: 225px;
    height: 150px;
    transform: rotate(10deg);
}
```

**Comment by omkark** [comment]
Hi @Mottie


Once I am applying rotate to both the images.
Both images are getting rotated properly.
But once I dynamically rotate image, the slider window is coming in other direction.

Do i need to reinitialize anythingzoomer function once css is changed

**Comment by Mottie** [comment]
I'm sorry, what slider window? Are you asking about AnythingSlider or AnythingZoomer?

**Comment by omkark** [comment]
Please check ths plunker
This has the problem
Please rotate and then hover
http://plnkr.co/edit/0j6BaOO8J1G6fCQKPvVw?p=preview

**Comment by Mottie** [comment]
As I shared above, only the images should be rotated. Here is an example ([demo](http://plnkr.co/edit/USHxBainLeznFjRc9X0b?p=preview))*

HTML

```html
<div ng-controller = 'MainCtrl'>
	<div class="rotate{{angle}}">
		<div id="zoom2">

			<div class="small">
				<img src="http://mottie.github.com/AnythingZoomer/demo/rushmore_small.jpg" alt="small rushmore">
			</div>

			<div class="large">
				<img src="http://mottie.github.com/AnythingZoomer/demo/rushmore.jpg" alt="big rushmore">
			</div>

		</div>
	</div>
	<button ng-click = 'rotate()'>Rotate</button>
</div>
```

CSS

```css
.rotate90 img {
  -webkit-transform : rotate(90deg);
  -ms-transform : rotate(90deg);
  transform : rotate(90deg);
}
.rotate180 img {
  -webkit-transform : rotate(180deg);
  -ms-transform : rotate(180deg);
  transform : rotate(180deg);
}
.rotate270 img {
  -webkit-transform : rotate(270deg);
  -ms-transform : rotate(270deg);
  transform : rotate(270deg);
}
```

Script

```js
var app = angular.module('plunker', []);

app.controller('MainCtrl', function($scope) {
	$scope.name = 'World';
	$("#zoom2").anythingZoomer();
	$scope.angle = 0;
	$scope.rotate = function()
	{
		$scope.angle = ( $scope.angle + 90 ) % 360;
	};

});
```


\* please be aware that I've never used angularjs before, so I couldn't get the controller to work when I moved the style from the one div to two images. So I opted to change the class name instead.
